server:
  port: 8091
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: myuser
      password: 111111
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false
debug: true
logging:
  level: debug