server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
debug: true
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.50.3.94:3306/mydatabase?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: myuser
      password: 111111
      maximum-pool-size: 5
      data-source-properties:
        data-source-properties: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: true
logging:
  level:
    root: debug
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
