server:
  port: 8091
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      data-source-class-name: com.mysql.cj.jdbc.MysqlDataSource
      jdbc-url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&useUnicode=true&characterEncoding=utf8
      jdbc-username: myuser
      jdbc-password: 111111
      maximum-pool-size: 10
      minimum-idle: 3
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false
debug: true
logging:
  level: debug